#' List files of a Zenodo repository
#' 
#' @description
#' Lists files of a Zenodo repository. If the repository is in restricted 
#' access, a token (argument `token`) must be provided.
#' 
#' @param record_id a `character` of length 1. The Zenodo identifier of the 
#'   repository (7 numbers). Can be found on the URL of the repository
#' 
#' @param token a `character` of length 1. A token generated by Zenodo to 
#'   access files of a restricted access.
#'
#' @return No returned value.
#' 
#' @export
#' 
#' @examples
#' # List files available in the repo: https://zenodo.org/record/7936568 ----
#' zen_list_files("7936568")

zen_list_files <- function(record_id, token) {
  
  # Check args ----
  
  if (missing(record_id)) {
    stop("Argument 'record_id' is required", call. = FALSE)
  }
  
  if (!is.character(record_id) || length(record_id) != 1) {
    stop("Argument 'record_id' must be a character of length 1", call. = FALSE)
  }
  
  if (!missing(token)) {
    
    if (!is.character(token) || length(token) != 1) {
      stop("Argument 'token' must be a character of length 1", call. = FALSE)
    }
  
  } else {
    
    token <- ""
  }
  
  
  # Build URLs ----
  
  user_raw_url <- full_raw_url(record_id, token)
  user_api_url <- full_api_url(record_id)
  
  
  # Generate cookies ----
  
  cookies  <- curl::new_handle()
  response <- curl::curl_fetch_memory(user_raw_url, handle = cookies)

  
  # Send request w/ cookies (~ token) ----
  
  response <- curl::curl_fetch_memory(user_api_url, handle = cookies)
  
  
  # Parse results ----
  
  metadata  <- jsonlite::fromJSON(rawToChar(response$"content"))
  
  
  # Check for token ----
  
  if (metadata$"metadata"$"access_right" == "restricted" && token == "") {
    stop(paste0("The repository is restricted. A token must be provided to ", 
                "access to the files.\nVisit <", user_raw_url, "> and request ",
                "access."), call. = FALSE)
  }
  
  
  # Get files names ----
  
  file_urls  <- metadata$"files"$"links"$"self"
  
  basename(file_urls)  
}
